pipeline {
    agent any
    stages {
        stage('Checkout from Git') {
            steps {
                git branch: 'master', url: 'https://github.com/paraspahwa/two-tier-flask-app-2.git'
            }
        }
        stage('Terraform version') {
            steps {
                sh 'terraform --version'
            }
        }
        stage('Terraform init') {
            steps {
                dir('Eks-terraform') {
                    withCredentials([string(credentialsId: 'snyk', variable: 'snyk')]) {
                        sh 'snyk auth $snyk'
                        sh 'terraform init && snyk iac test --report || true'
                    }
                }
            }
        }
        stage('Terraform validate') {
            steps {
                dir('Eks-terraform') {
                    sh 'terraform validate'
                }
            }
        }
        stage('Terraform plan'){
             steps{
                 dir('Eks-terraform') {
                      sh 'terraform plan'
                   }
             }
        }
        stage('Terraform apply/destroy'){
             steps{
                 dir('Eks-terraform') {
                      script {
                          sh 'terraform ${action} --auto-approve'
                      }
                   }
             }
        }
    }
}
